{"timestamp":"2025-09-23T06:49:55.588835","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-23T06:49:55.589295","level":"info","event":"Filling up the DagBag from dags/update_db.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-23T06:49:55.608598Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T06:49:55.608696Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T06:49:55.608815Z","level":"info","event":"Current task name:read_json","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T06:49:55.608887Z","level":"info","event":"Dag name:update_db","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T06:49:55.610196","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"Exception","exc_value":"Erreur lors de la lecture du fichier json dans staging area","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/workspaces/youtube_etl_pipeline/.venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/workspaces/youtube_etl_pipeline/.venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/workspaces/youtube_etl_pipeline/.venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/workspaces/youtube_etl_pipeline/.venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/workspaces/youtube_etl_pipeline/.venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/workspaces/youtube_etl_pipeline/.venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/workspaces/youtube_etl_pipeline/dags/update_db.py","lineno":15,"name":"read_json"}],"is_group":false,"exceptions":[]},{"exc_type":"FileNotFoundError","exc_value":"[Errno 2] No such file or directory: '{DIR_FILE}/data_youtube_extract.json'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/workspaces/youtube_etl_pipeline/dags/update_db.py","lineno":11,"name":"read_json"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-23T06:49:55.624335Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T06:49:55.624501Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T06:49:55.624607Z","level":"info","event":"Task:<Task(PythonOperator): read_json>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T06:49:55.624719Z","level":"info","event":"Failure caused by Erreur lors de la lecture du fichier json dans staging area","chan":"stdout","logger":"task"}
